// flow-typed signature: 334040c8e08f8e03c3c6c6f35505bf03
// flow-typed version: <<STUB>>/@types/react_v^16.4.14/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
